kind: Service
apiVersion: v1
metadata:
  name: k8s-demo-go-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: k8s-demo-go
  ports:
    - port: 80
      targetPort: 8080
      name: http
